language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpcsclite-dev libgcrypt11-dev
script: autoreconf -vfi && ./configure && make && make check
before_deploy:
  - make distcheck
  - export RELEASE_PKG_FILE=$(ls *.tar.*)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: nt0vm42oMDDR5wG9QJbhDuEd+dCHE0oJlNo2XkDxkrIdPwZkggEAUlL9+OabXiGAiUyC3Fs8idz+GSUlG+51N3zruS4XwdbI21xv5EOq4JCXeX0+9Fq+2WU76rD50Rx+VxaYxlBTWVjrp6UDUX9jvia4t0XH18NKzpSJNTypctDQ0tAcKg24/4pOHCA2awNZIvNREuujFcF/DUUti+V3xv8Bv1O63BtC6xMyLe2TTcFOEP9NJcRSbaYSe8KbR/3jkRgKoMbHYmDLEAjpYmBqUKldta5YE9RPmsxe06VBtb2n+V2qysuFcPRUDbCyiVPKGxzh1t2vQr4vTv88MAqm5k9u3+UOhhVdOlh5U/dudgBxdCwxiHRelOnUHbGtDZMsnlbC4Oq3zdaBSjuzdYrDis5+N6hElu/Ul0cl2VufWetDDqgsVqfeIBmoiDYPRZ4jQ7pt8FazQXEvmS5ETkcjwNpMeLzD/W1J63VVV5TXd7Q2WAkiXW1O5vlpBloAJChHsGgwsGoLsfPTvMKgpjZuuc1/xaWs7/POJFx1W+0u7WCk9Huu/fzRWzKg3DqRM7gGnW6mUFqFtRYqt5QES9pATuyp1iUmOSAwMonthpOkrHVNZlFUMIfI0/vNSlllEnDa0bjGeulOVzzLReXtzd8spLs0nZFLU5NDQP7JHayJalE=
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  on:
    tags: true
