language: c
sudo: false
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - libconfig-dev
      - libpcsclite-dev
      - libgcrypt11-dev
      - nettle-dev
env:
  - GCRYPT=yes NETTLE=no
  - GCRYPT=no NETTLE=yes
script: autoreconf -vfi && mkdir -p build && cd build && ../configure --enable-scard-emu --enable-scard-apduio --enable-crypto-libgcrypt=${GCRYPT} --enable-crypto-nettle=${NETTLE} && make && make check
